
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AVANZAR GIRARDERECHA GIRARIZQUIERDA PTCOMAinit            : instruccionesinstrucciones    : instrucciones instruccioninstrucciones    : instruccion instruccion      : avanzar_instr\n                        | girarderecha_instr\n                        | girarizquierda_instr avanzar_instr  : AVANZAR PTCOMAgirarderecha_instr : GIRARDERECHA PTCOMAgirarizquierda_instr : GIRARIZQUIERDA PTCOMA'
    
_lr_action_items = {'AVANZAR':([0,2,3,4,5,6,10,11,12,13,],[7,7,-3,-4,-5,-6,-2,-7,-8,-9,]),'GIRARDERECHA':([0,2,3,4,5,6,10,11,12,13,],[8,8,-3,-4,-5,-6,-2,-7,-8,-9,]),'GIRARIZQUIERDA':([0,2,3,4,5,6,10,11,12,13,],[9,9,-3,-4,-5,-6,-2,-7,-8,-9,]),'$end':([1,2,3,4,5,6,10,11,12,13,],[0,-1,-3,-4,-5,-6,-2,-7,-8,-9,]),'PTCOMA':([7,8,9,],[11,12,13,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'init':([0,],[1,]),'instrucciones':([0,],[2,]),'instruccion':([0,2,],[3,10,]),'avanzar_instr':([0,2,],[4,4,]),'girarderecha_instr':([0,2,],[5,5,]),'girarizquierda_instr':([0,2,],[6,6,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> init","S'",1,None,None,None),
  ('init -> instrucciones','init',1,'p_init','gramatica.py',51),
  ('instrucciones -> instrucciones instruccion','instrucciones',2,'p_instrucciones_lista','gramatica.py',55),
  ('instrucciones -> instruccion','instrucciones',1,'p_instrucciones_instruccion','gramatica.py',61),
  ('instruccion -> avanzar_instr','instruccion',1,'p_instruccion','gramatica.py',65),
  ('instruccion -> girarderecha_instr','instruccion',1,'p_instruccion','gramatica.py',66),
  ('instruccion -> girarizquierda_instr','instruccion',1,'p_instruccion','gramatica.py',67),
  ('avanzar_instr -> AVANZAR PTCOMA','avanzar_instr',2,'p_instruccion_avanzar','gramatica.py',72),
  ('girarderecha_instr -> GIRARDERECHA PTCOMA','girarderecha_instr',2,'p_instruccion_girarderecha','gramatica.py',76),
  ('girarizquierda_instr -> GIRARIZQUIERDA PTCOMA','girarizquierda_instr',2,'p_instruccion_girarizquierda','gramatica.py',80),
]
